### ISSUE TITLE
ID with multibytes words

### ISSUE THREAD

**Issue by asturur** [googlei18n/noto-emoji#121]
Hello,

i m happily using this emoji set.

I notice that sometimes the SVGS have an id with some multibyte word as descriptor ( to me they appear as japanes characters )
While this is maybe regular, it is not in all SVGS but break the possibility running window.btoa in javascript over the svg content.

Since i see no usefulness in exporting those IDs, i was asking if is possible to remove them.

**Comment by DeeDeeG** [comment]
(FWIW, I ran it through Translate, and I believe it means "Layer 1," in Japanese, especially since it is phonetic, and reads as "Lei-ya 1" see: [translate](https://translate.google.com/#auto/en/%22%E3%83%AC%E3%82%A4%E3%83%A4%E3%83%BC_1%22); [another translation](https://translate.google.com/translate?sl=auto&tl=en&js=y&prev=_t&hl=en&ie=UTF-8&u=https%3A%2F%2Fja.wikipedia.org%2Fwiki%2F%25E3%2583%25AC%25E3%2582%25A4%25E3%2583%25A4%25E3%2583%25BC&edit-text=)) (Also, this seems to be a thing Illustrator does, regardless of language: [blog post about this](http://s10wen.com/blog/2014/07/09/illustrator-svg-id-issue/))

This can be addressed with SVGO, using the CleanupIDs feature. Here are ways to get/use SVGO https://github.com/svg/svgo#other-ways-to-use-svgo. 

(I'm not sure which is the easiest/fastest way, but I can confirm it works, because I tried [SVGOMG](https://jakearchibald.github.io/svgomg/) on one emoji, and it did successfully remove the id="Layer_1" part.)

**Comment by asturur** [comment]
sure i was planning to use SVO, i m asking if you accept a PR of removing the ID on this repo.

**Comment by dougfelt** [comment]
The issue is that none of the SVG or PNG images actually originate in this repo.  The flags are copies of those from upstream https://github.com/behdad/region-flags.  The other emoji originate in google internal Adobe Illustrator files.  These have not been cleared for opensource release as they are working documents used by the designers and frequently contain random reference images in addition to the artboard content that gets exported.  When we get new updates from designers, we generate new SVG and PNG from these AI files and replace whatever is in the repo.  Thus any changes to those files will get overwritten.

**Comment by asturur** [comment]
i understand perfectly.
I will clean them and keep them as an alternative resource on a fork.
