### ISSUE TITLE
CSS font-awesome type use

### ISSUE THREAD

**Issue by mika76** [googlei18n/noto-emoji#131]
Is there any way to use this like font-awesome through css?

**Comment by will-e-yams** [comment]
It's possible: I just made a proof of concept that works. However, the icons showing are quite different from the ones on https://www.google.com/get/noto/help/emoji/ Rather than showing the Android-style, they're more generic, round emoticons.

**Comment by mika76** [comment]
Which means that you're not actually using this font and your concept didn't work...

**Comment by mika76** [comment]
Closed without even a comment?

**Comment by DeeDeeG** [comment]
First, I want to do a basic description of font-awesome's technology so we are all on the same page:

font-awesome uses a black-and-white font, and makes use of the Unicode Private Use Area ("PUA") so as to not overlap with other codepoints... And delivers this as a Web Open Font File ("WOFF") for better performance on the web.

Ok, so making a font that encodes these emoji into the Private Use Area should be doable, no problem.

And saving as a WOFF should also not be a problem.

It's the black and white part that would be a problem. CSS can't do a lot with multicolor fonts right now, I'm guessing. (Haven't tried it myself, so who knows until someone tries it and posts results).

I'd say it depends on why you want a font-awesome style font. If the features you want don't work with multicolor fonts (such as changing the color of the emoji with CSS), you're out of luck at the moment. Otherwise it might work. Let us know what features you like from font-awesome and someone can try to figure out whether that can be done.

**Comment by mika76** [comment]
Hey @DeeDeeG thanks for the questions. Basically the question is more like can this be used without downloading anything youself and hosting yourself, and just link it via a cdn...

**Comment by twardoch** [comment]
Not quite yet. There are four different "flavors" of color glyph storage in OpenType (SVG and COLR are outline-based, CBDT and sbix are bitmap-based). Each web browser supports a different flavor (Edge on Windows 10 does all four, Firefox does SVG and for Chrome and Safari it's... complicated). So currently, any direct use of color fonts in CSS is still really complicated. You'd be better off with using there source images at this point.

**Comment by DeeDeeG** [comment]
> Basically the question is more like can this be used without downloading anything youself and hosting yourself, and just link it via a cdn...

There's no third-party CDN option at the moment as far as I know. Sorry to say.

Going a bit off-topic:

If anyone is wondering if using it as a web font is doable, someone has already demoed that in the comments of #36.

@twardoch is right, there's not an easy solution that works everywhere that font-awesome does right now. Color font support is a bit mixed compared to black and white fonts.

In my experience though, Firefox supports CBDT. I believe Chrome does too. And apparently Edge does as well. The odd one out would be Safari, then, and various older browsers with *no* color font support whatsoever.

Unless you find a way to make this as an SBIX font (Apple's font format), you'd only be able to support Firefox, Chrome, and Edge. But yeah I'm pretty sure that can all be done. (I believe there is an open-source SBIX font maker somewhere...)

It sounds like you don't want to host it yourself, but I think it's worth pointing out that self-hosting and using as a web font is fundamentally doable. Web font usage is actually one of the best-supported use cases right now. It's using it as a system font outside the browser that is giving the most headaches.

**Comment by mika76** [comment]
Cool, thanks guys for the answers...
