### ISSUE TITLE
So many Emojis not colors!!

### ISSUE THREAD

**Issue by taher095** [googlei18n/noto-emoji#150]
U+2639
U+2602
U+26D1
U+2618
U+26C8
U+2603
U+2604
U+26F7
U+26F8
U+26F0
U+26E9
U+26F4
U+2708
U+26F1
U+2620
U+23F1
U+23F2
U+2328
U+2709
U+270F
U+2712
U+2702
U+26CF
U+2692
U+2694
U+2699
U+2697
U+26D3
U+26B0
U+26B1
U+2763
U+2668
U+26A0
U+2622
U+2623
U+2B06
U+2197
U+27A1
U+2198
U+2B07
U+2199
U+2B05
U+2196
U+2195
U+2194
U+21A9
U+21AA
U+2934
U+2935
U+269B
U+2721
U+2638
U+262F
U+271D
U+2626
U+262A
U+262E
U+25B6
U+25C0
U+267B
U+2611
U+2714
U+2716
U+303D
U+2733
U+2734
U+2747
U+203C
U+2049
U+A9
U+AE
U+2122
U+1F170
U+1F171
U+2139
U+24C2
U+1F17E
U+1F17F
U+1F202
U+1F237
U+3297
U+3299
U+25AA
U+25AB
U+25FB
U+25FC

all this emojis with Unicode versions 1.1 to 6.0
img to issue
[
![image](https://user-images.githubusercontent.com/30312850/28409445-61a55e9c-6d43-11e7-8ff7-c552bdddf5f5.png)
](url)
[
![image](https://user-images.githubusercontent.com/30312850/28409479-7663b374-6d43-11e7-9d69-fd27f7e7b834.png)
](url)

**Comment by dougfelt** [comment]
I haven't looked at all of these, but all the characters I did look at have default text presentation according to the Unicode data in emoji-data.txt.  Android overrides a few of these to give them default emoji presentation, I don't have a list of those.

This means that if there is a b/w font in the fallback chain that contains these characters Android will prefer it to a color emoji font.  This is because Unicode says the default behavior is to show them in 'text' style.

Unicode allows you to request that emoji characters be shown in a different presentation from the default. In the latest android OS prerelease (and perhaps sooner, I don't quite remember when this was enabled) you can explicitly request emoji presentation by following the emoji codepoint with the emoji variation selector codepoint U+FE0F.  Try rendering "\u2638\ufe0f" and see what you get.

Note that different phone manufacturers shipping Android-based phones might use different fonts or organize their fallback support differently.  So this still might not work on some Android phones even with the latest release.

**Comment by Superagius** [comment]
Hi
