### ISSUE TITLE
Any way to import all of the SVG files into VectorDrawable files ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [googlei18n/noto-emoji#161]
In order to use nicely on Android, we could use VectorDrawable. 
Is it possible?
Of course, some of the SVG files are problematic (have gradients, for example), but maybe the flags are ok?

Is there any batch tool to convert them all, and if there is an issue, skip the problematic files?

**Comment by dougfelt** [comment]
The flag SVG do not match the images used in the font, so if that matters to you that won't help.

A large number of the images use gradients, so if VectorDrawable doesn't support them that is likely to be an issue.

I don't program on Android and am not familiar with VectorDrawable or tools that might be available for it, perhaps others can answer that question.

**Comment by AndroidDeveloperLB** [comment]
"The flag SVG do not match the images used in the font, so if that matters to you that won't help."
What do you mean? I mean those (countty) flags :
https://github.com/googlei18n/noto-emoji/tree/master/third_party/region-flags

VectorDrawable is quite basic, sadly. It doesn't support gradients and text, and probably other things I never knew about on SVG.

Isn't this repo of Google? Can you please ask an Android developer from there?

**Comment by dougfelt** [comment]
> "The flag SVG do not match the images used in the font, so if that matters to you that won't help."
> What do you mean? I mean those (countty) flags :
I mean, if you look at the images rendered by the font, and look at the SVG, they're different.  That's because the font uses PNG internally.  The PNG flag images used in the font have a transform applied to them after the SVG is converted to PNG that applies a wave and a shadow effect.  The raw SVG images don't have this, so they look different.

> Isn't this repo of Google? Can you please ask an Android developer from there?
It's a weekend here.  I only know one or two Android engineers, we'll see if they know anyone.  You might try asking on one of the Android developer forums, I'm not familiar with them.

**Comment by AndroidDeveloperLB** [comment]
Sorry I still don't get it.
What's wrong with the SVG files of the country flags? To me they look ok. I don't mind the font. I asked about the SVG files alone (or PNG files if some SVGs are a problem to convert).

**Comment by dougfelt** [comment]
There's nothing wrong with the SVG files of the country flags **if** you don't care that they don't match what's in the color emoji font.  That's why I said "if it matters to you" in my original reply.

These flags do not originate with this repo, btw, they originate in https://github.com/behdad/region-flags.  You might try looking there if you have questions about them in particular.

**Comment by AndroidDeveloperLB** [comment]
Don't match in which way? Can you provide an example? Maybe a visual example?

Thank you for the link. All files here are free to use, right? I'm not familiar with SIL  license... Is it similar to Apache?

**Comment by dougfelt** [comment]
All images are free subject to whatever license constraints are listed. The data is under the Apache license, the font is under the SIL license.  I can't get more specific because I'm not allowed to provide legal advice, sorry.

For example:
original (png corresponding to svg, since github won't attach svg): ![au](https://user-images.githubusercontent.com/9939212/29753323-f1eae852-8b23-11e7-8e43-b41eb41de22a.png)
font: 
![emoji_u1f1e6_1f1fa](https://user-images.githubusercontent.com/9939212/29753332-28347fcc-8b24-11e7-9eac-3ced16ef4512.png)

In addition to the dimensions being different, you'll note the font image has a wave and shadow border (and all font PNGs are the same dimensions, while the svg sources do not have consistent native dimensions although they scale)

**Comment by AndroidDeveloperLB** [comment]
Oh this makes sense. They don't seem so different. 
Say, can you also publish the blobs emojis? I miss them, and so does a lot of Android fans out there:
https://issuetracker.google.com/issues/62256231
https://issuetracker.google.com/issues/38440592

**Comment by asturur** [comment]
You can recover them from the commit history.

2017-08-27 21:55 GMT+02:00 AndroidDeveloperLB <notifications@github.com>:

**Comment by AndroidDeveloperLB** [comment]
Recover? Are they dead ? 
:(
Please reconsider bringing them back
