### ISSUE TITLE
Missing Emojis in Latest Commit.

### ISSUE THREAD

**Issue by aggarwal-dev** [googlei18n/noto-emoji#168]
Hey,

As mentioned here: https://emojipedia.org/google/android-8.0/
The latest commit should contain 2,669 emojis while the latest commit contains only 2,182 emojis.

I had a hard time figuring out which all emojis were missing from the commit and I must point out that all the flags emojis are missing.
I would really appreciate if users can point out more emojis.

And I hope someone will provide us a fix soon for the same.

Regards,
Dev Aggarwal

**Comment by dougfelt** [comment]
All the unique sources needed to build the NotoColorEmoji font are present in the repo.

The sources are designed for building the font.  In this font, several emoji sequences share the same image, in particular almost all gender-neutral sequences share images with one of the gendered sequences.  We do not have separate copies of these images, because this can lead over time to incomplete updates or unwanted differences accumulating in the data.  The definitions of these shared images are in the aliases.txt file.  There is a tool that can be used to generate copies of image files based on these aliases, it may be slightly out of date though as it is not part of our main tooling.

The flag source are available, but those do not match the images in the font.  We preserve the sources in the repo and not the final versions.  The font uses PNG images generated through scaling, warping, and applying shading transforms to the source flags images.  We have no tooling to produce SVG flag images because we currently do not have tooling to apply the shading and wave transforms to the SVG source.
