### ISSUE TITLE
ImportError: No module named nototools

### ISSUE THREAD

**Issue by 4cm4k1** [googlei18n/noto-emoji#175]
I cloned the nototools repo and ran `brew install --with-cairo harfbuzz cairo pango pygtk imagemagick`, `pip install -r requirements.txt`, and `python setup.py develop`. And then I cloned this repo and ran `make`, getting the following message:

```python
Traceback (most recent call last):
  File "./flag_glyph_name.py", line 25, in <module>
    import add_emoji_gsub
  File "/Users/4cm4k1/Code/noto-emoji/add_emoji_gsub.py", line 28, in <module>
    from nototools import font_data
ImportError: No module named nototools
```

I've tried a few things to try to fix it, but I've had no luck. Would anyone have a suggestion?

* **Python versions:** 2.7.14, 3.6.3
* **macOS version:** 10.13.1 Beta 2

**Comment by anthrotype** [comment]
hello @4cm4k1 

can you successfully `import nototools` from the Python interactive shell or does it give you `ImportError` there as well?

How did you install python? Homebrew, or Apple's built-in python, or pyenv, etc?

If you have multiple pythons, make sure you run the noto-emoji scripts with the same python used to install nototools.

Are you using any virtual environments, or have you manipulated manually your $PYTHONPATH?

What does `pip --version` show as python version and site-packages folder? Make sure it is linked with the expected `python` binary.

Try to call pip as `python -m pip ...` (or `python3 -m pip ...`) instead of just `pip`, as that explicitly runs pip for a specific python binary and may avoid this confusion.

**Comment by dougfelt** [comment]
Please reopen if you're still having trouble with this.
