### ISSUE TITLE
Building noto-emoji fails with convert error

### ISSUE THREAD

**Issue by juanitotc** [googlei18n/noto-emoji#179]
Building from git as of today fails with the imagemagick convert (ImageMagick 6.9.5-8 Q16 x86_64 2016-09-04) error below - is this because as of ImageMagick 6.5.4-7 2014-02-10, paths are not supported with @ syntax?

make
...
Compiler: gcc
     Debug: no
       SSE: yes
    OpenMP: no
    libpng: shared (1.6.29)
      zlib: shared (1.2.8)
     lcms2: shared (2.7)
...
using optipng
mkdir -p "build/compressed_pngs"
cc waveflag.c -o waveflag -std=c99 -Wall -Wextra `pkg-config --cflags --libs cairo` -lm `pkg-config --libs cairo`
mkdir -p "build/flags"
mkdir -p "build/resized_flags"
mkdir -p "build/renamed_flags"

convert: unable to open image `canvas:none': No such file or directory @ error/blob.c/OpenBlob/2705.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/504.
convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504.
convert: no images defined `PNG32:build/resized_flags/AC.png' @ error/convert.c/ConvertImageCommand/3257.
make: *** [Makefile:171: build/resized_flags/AC.png] Error 1
Command exited with non-zero status 2

**Comment by dougfelt** [comment]
I'm using ImageMagick 6.8.9-9 Q16 x86_64 2017-03-12.  Works for me.

Maybe you can unhide the command in the Makefile to see what is actually getting passed to convert?

**Comment by juanitotc** [comment]
"$(MAKE) V=1" doesn't help - sorry, but what do you mean by "unhide the command in the Makefile"?

**Comment by dougfelt** [comment]
remove the leading '@' from the command line in the makefile.  It suppresses echoing the command line.  Then we can see what the command line is that is being passed to convert.

**Comment by juanitotc** [comment]
cc waveflag.c -o waveflag -std=c99 -Wall -Wextra `pkg-config --cflags --libs cairo` -lm `pkg-config --libs cairo`
mkdir -p "build/flags"
mkdir -p "build/resized_flags"
mkdir -p "build/renamed_flags"
./waveflag build/flags/ "third_party/region-flags/png/AC.png"
convert -size 136x128 canvas:none -compose copy -gravity center "build/flags/AC.png" -composite "PNG32:build/resized_flags/AC.png"
convert: unable to open image `canvas:none': No such file or directory @ error/blob.c/OpenBlob/2705.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/504.
convert: no decode delegate for this image format `PNG' @ error/constitute.c/ReadImage/504.
convert: no images defined `PNG32:build/resized_flags/AC.png' @ error/convert.c/ConvertImageCommand/3257.
make: *** [Makefile:171: build/resized_flags/AC.png] Error 1

**Comment by juanitotc** [comment]
Ah - got it - the imagemagick development files are required - once these are added things work.

Sorry for the noise.

**Comment by juanitotc** [comment]
..things work, but fail with the error below, which I presume means python-2.7.x must be built with "--enable-unicode=ucs4"

Loaded font 'NotoColorEmoji.tmpl.ttf'.
Font metrics: upem=2048 ascent=1900 descent=500.

Looking for images matching 'build/compressed_pngs/emoji_u*.png'.
Traceback (most recent call last):
  File "third_party/color_emoji/emoji_builder.py", line 543, in <module>
    main (sys.argv)
  File "third_party/color_emoji/emoji_builder.py", line 467, in main
    uchars = "".join ([unichr(cp) for cp in cps if not is_vs(cp)])
ValueError: unichr() arg not in range(0x10000) (narrow Python build)
make: *** [Makefile:215: NotoColorEmoji.ttf] Error 1
rm build/emoji/emoji_u1f512.png NotoColorEmoji.tmpl.ttx

**Comment by dougfelt** [comment]
On Oct 27, 2017 11:59 PM, "juanitotc" <notifications@github.com> wrote:

..things work, but fail with the error below, which I presume means
python-2.7.x must be built with "--enable-unicode=ucs4"

Yes, that's correct.

Loaded font 'NotoColorEmoji.tmpl.ttf'.
Font metrics: upem=2048 ascent=1900 descent=500.

Looking for images matching 'build/compressed_pngs/emoji_u*.png'.
Traceback (most recent call last):
File "third_party/color_emoji/emoji_builder.py", line 543, in
main (sys.argv)
File "third_party/color_emoji/emoji_builder.py", line 467, in main
uchars = "".join ([unichr(cp) for cp in cps if not is_vs(cp)])
ValueError: unichr() arg not in range(0x10000) (narrow Python build)
make: *** [Makefile:215: NotoColorEmoji.ttf] Error 1
rm build/emoji/emoji_u1f512.png NotoColorEmoji.tmpl.ttx

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/googlei18n/noto-emoji/issues/179#issuecomment-340150625>,
or mute the thread
