### ISSUE TITLE
List of character mapping and CLDR

### ISSUE THREAD

**Issue by Extarys** [googlei18n/noto-emoji#215]
Is there a list of CLDR associated with the noto emojis somewhere?

**Comment by dougfelt** [comment]
I guess you're looking for annotations/alternate names in various languages? 

You should probably ask the CLDR or ICU folks.  We just use the raw Unicode data files.  I think we do some custom name tweaking when generating overview pages for the noto site, but beyond that we don't do anything special that would need CLDR info, so I don't know.

**Comment by Extarys** [comment]
Ok thanks!

**Comment by brawer** [comment]
See here:

https://unicode.org/cldr/charts/latest/annotations/index.html

https://unicode.org/cldr/trac/browser/trunk/common/annotations

**Comment by Extarys** [comment]
Yes thanks. Does Noto follow the standard in term of range, etc or is there any exceptions that I should be aware of? (I'm building a emoji plugin based on noto)

**Comment by dougfelt** [comment]
Noto deviates from the standard in only a few places, to be compatible with legacy Android behavior.  Noto supports skin tone variants for the wrestlers and handshake emoji (1f93c and 1f91d).  Unicode currently provides no mechanism whereby the two wrestlers or two arms can have different skin tones, so opted to not support skin tones for these.  When these were first introduced Android did, though, so we continue to do so.

The default build of NotoColorEmoji omits a few region flags that the repo has assets for, this reflects Android's behavior.  Most other emoji providers support the full set of flags.  You can see this in the ['full emoji list'](https://unicode.org/emoji/charts/full-emoji-list.html) table on the Unicode site.  This can be controlled in the Makefile.

We generally represent non-gendered emoji sequences using one of the gendered images, for example person bowing (1f647) uses a male image, and person facepalming (1f926) uses a female image.  Unicode doesn't require any particular gender for these and the assignment is more or less arbitrary, though the images for sequences introduced in earlier versions of Unicode follow typical gender stereotypes.  This is controlled in the emoji_aliases.txt file.  We do not provide true gender-neutral versions for most of these non-gendered sequences (the earlier 'blob' design was better at this).

We've made no attempt to make the build system fully customizable so that you could make up your own emoji sequences.  That said, we don't go out of our way to prevent it.  If you provide images following the naming conventions the build will attempt to construct a font that recognizes those sequences.  Note though that many rendering environments (e.g. Chrome) strictly follow the Unicode specified sequences and will generally not render sequences they believe to be invalid as single emoji, even if the font would otherwise support it.  This frequently means that for a brief period around the time each year when the Unicode standard updates, a browser might not render a new emoji sequence as expected until the browser has had a chance to update.
