### ISSUE TITLE
Please clarify small metrics change

### ISSUE THREAD

**Issue by jbicha** [googlei18n/noto-emoji#233]
I'm trying to read https://github.com/googlei18n/noto-emoji/commit/e571d53e0299bd1 but I'm a bit confused.

The commit message says
> android has legacy tooling that expects small metrics.  we leave the default in emoji_builder to use big metrics but in the makefile default the flag we pass to request small metrics.

By my reading, we actually used big metrics before this change. Is that correct?

What are the practical differences between small and big metrics here?

Background
----------------
My context is that I help maintain this font's package in Debian and Ubuntu where this font is the default color emoji for GNOME. I am trying to [update](https://launchpad.net/bugs/1788256) this font to the August 2018 version in Ubuntu 18.04 LTS. Ubuntu's update policy is to try to introduce the least amount of changes necessary.

**Comment by dougfelt** [comment]
Until fairly recently we used small metrics tables only.  I had accepted a submission to switch to large metrics, as it should have not changed behavior, however it turned out some folks had tooling that expected the small metrics that they were unable to readily change.  So this change introduces the ability to select whether to generate small metrics tables or large metrics via a flag, and defaults to small metrics.  The font that we post on the site is built with the default settings and so uses small metrics tables.

The purpose in switching to large metrics tables was to support vertical layout using vertical metrics tables, so the default build does not provide these and vertical layout might have issues.  I personally have not evaluated vertical layout.

**Comment by jbicha** [comment]
Ok, I see you're referring to https://github.com/googlei18n/noto-emoji/commit/a9d16062fb

Ubuntu did package the flag and pistol updates so Ubuntu 18.04 LTS did originally build the big metrics version.

Do you think users would notice a change by Ubuntu switching back to small metrics now?

**Comment by dougfelt** [comment]
They shouldn't for horizontal text, but I don't have a test handy.
