### ISSUE TITLE
Flag of Switzerland should be square

### ISSUE THREAD

**Issue by roubert** [googlei18n/noto-emoji#34]
The current emoji for the flag of Switzerland is rectangular, which is incorrect, it should be square. Wikipedia has references to the relevant standards and regulations:
https://en.wikipedia.org/wiki/Flag_of_Switzerland

**Comment by roozbehp** [comment]
This is kinda working as intended. The sources have the right proportions, but we add code to make them "consistent". Otherwise it would be very hard to properly show the square flags of Switzerland and Vatican City on one side and the very long flag of Qatar (11:28) on the other side all in an "emoji square". The flag of Nepal is a whole other issue too...

There's language in UTR #51 about this: http://www.unicode.org/reports/tr51/#Flags

**Comment by roubert** [comment]
I do note that UTR #51 also suggests presenting the Swiss flag as square with "white bands on the side" and that this indeed also is how it is presented in the Unicode Emoji Charts. (A non-square Swiss flag just looks so jarringly wrong to me ...)

**Comment by AlexandreBonneau** [comment]
Do not add "white bands on the side", since some of us do not use the default bright white background, but a dark one.

![github_black_background](https://cloud.githubusercontent.com/assets/7248877/22222593/90697bec-e15b-11e6-8ba2-7ab222048d1a.png)

Instead, use a `.png` with transparent borders!

**Comment by roubert** [comment]
[UTR #51](http://www.unicode.org/reports/tr51/#Flag_Presentation) has already been updated to now instead use this wording:

> a blank band

**Comment by behdad** [comment]
Our latest style takes care of this.  Compare:
![waved-ch](https://cloud.githubusercontent.com/assets/142891/22228900/f98832bc-e188-11e6-9295-5e76aaa5e819.png)
![waved-de](https://cloud.githubusercontent.com/assets/142891/22228901/f989b984-e188-11e6-90a7-a033e0236230.png)
