### ISSUE TITLE
missing some emojis

### ISSUE THREAD

**Issue by zhouchaohong1111** [googlei18n/noto-emoji#61]
1f469_200d_2764_fe0f_200d_1f48b_200d_1f468
1f469_200d_2764_fe0f_200d_1f468
1f468_200d_1f469_200d_1f466
this three emoji is missing.

**Comment by dougfelt** [comment]
The particular issue here is that while the glyphs are present in the B/W emoji font with a cmap entry mapping a single character to each (couple with heart 1f491, kiss 1f48f, and family 1f46a), there are no GSUB entries that map these sequences to them.

**Comment by brawer** [comment]
Noto is an open-source project. If anyone wants to make this change, feel free to send a patch (GitHub pull request) for adding a [features.fea file](http://unifiedfontobject.org/versions/ufo3/features.fea/) to the [sources](https://github.com/googlei18n/noto-source/tree/master/src/NotoEmoji) that defines the needed glyph substitutions.

**Comment by DeeDeeG** [comment]
I am working on this, and my features.fea looks like this:

```
feature liga {
  sub u1f469 [zero width joiner?] u2764 [variation selector 16?] [zero width joiner?] u1f48b zero u1f468 by 1f469_200d_2764_fe0f_200d_1f48b_200d_1f468
  sub u1f469 [zero width joiner?] u2764 [variation selector 16?] [zero width joiner?] u1f468 by 1f469_200d_2764_fe0f_200d_1f468
  sub u1F468 [zero width joiner?] u1F469 [zero width joiner?] u1F466 by 1f468_200d_1f469_200d_1f466
} liga;
```
Given that the syntax for each individual ligature should be:

`  sub [glyph 1] [glyph 2] [etc...] by [glyph_name_to_replace_with]`

I'm not sure how to account for [zero width joiners](http://www.fileformat.info/info/unicode/char/200d/index.htm), or [variation selectors](http://www.fileformat.info/info/unicode/char/fe0f/index.htm). I notice that there are no glyphs for those in the glyphs folder. Any suggestions?

**Comment by brawer** [comment]
Add empty glyphs such as `uni200D`, `uniFE0F`, etc.?

**Comment by DeeDeeG** [comment]
> Add empty glyphs such as uni200D, uniFE0F, etc.?

Okay, sounds good. Had to read up on the [.GLIF](http://unifiedfontobject.org/versions/ufo3/glyphs/glif/) documentation, but it looks straight-forward.

**Comment by DeeDeeG** [comment]
## As a design consideration, could some Google folks weigh in on what sequences should map to Family, Couple w Heart, and Couple Kissing?

([reference images of the b/w Noto glyphs](https://gist.github.com/DeeDeeG/628eb0db21ae8155767607d17a0f44fe))

### I think these are pretty obvious:

- `Woman + Heart + Man` --> `Couple w Heart` || 👩❤👨 --> 💑
- `Woman + Heart + Kiss mark + Man` --> `Couple Kissing` || 👩❤💋👨 --> 💑

### Family is less clear, as there is no one official sequence for this, and there are lots of options.

- `Man + Woman + Girl + Boy` --> `Family` || 👨👩👧👦 --> 👪
(matches the glyph in this font exactly, and matches Facebook Messenger)
- `Man + Woman + Boy` --> `Family` || 👨👩👦 --> 👪
(Matches [family in most recent emoji fonts](http://emojipedia.org/family/))
- `Man + Woman + Girl` --> `Family` || 👨👩👧 --> 👪
(Matches Samsung)

### Is it best to add ligatures for same-sex couples, single-parent families, single-child families?

- `Man + Man + Girl + Boy` --> `Family` || 👨👩👧👦 --> 👪
- `Woman + Woman + Girl` --> `Family` || 👨👩👧👦 --> 👪
- `Man + Woman + Girl` --> `Family` || 👨👩👧 --> 👪
- `Woman + Heart + Woman` --> `Couple w Heart` || 👩❤👩 --> 💑
- `Man + Heart + Kiss mark + Man` --> `Couple Kissing` || 👨❤💋👨 --> 💑
- `etc.`

(Given that the current glyphs are rather opposite-sex looking, and the current "family" glyph has two parents and two kids, my instinct is to not add these sequences. However, if gender-neutral glyphs were provided it could work. It could also work if the many gender-specific glyphs were added.)

(I do think the current couple-kissing glyph is a plausible representation for a "`woman+heart+kiss mark+woman`-->`couple kissing`" sequence, and to a lesser extent the current family glyph is plausible as a "`woman+woman+girl+boy`-->`family`" sequence, but that's pretty much it. The long haired parent has a distinctly female hairstyle. The round headed parent could conceivably be either gender.)

### Lastly, should we do "out-of-order" sequences? No standard emoji keyboard would generate these, and it's hard to do them by hand with all the required zero-width joiners, so it probably doesn't matter:

- `Man + Heart + Woman` --> `Couple with Heart` || 👨❤👩 --> 💑
- `Man + Heart + Kiss mark + Woman` --> `Couple kissing` || 👨❤💋👩 --> 💑
- `Woman + Man + Boy + Girl` --> `Family` || 👩👨👦👧 --> 👪

**Comment by brawer** [comment]
Actually, this is not really a design consideration. Emojis should work across all platforms, so it’s prescribed by Unicode which sequences should be supported. Have a look at [Unicode Technical Report 51](http://unicode.org/reports/tr51/index.html), which links to [data files](http://unicode.org/reports/tr51/index.html#emoji_data). A more visual table is at [Full Emoji Data v4](http://unicode.org/emoji/charts/full-emoji-list.html), which will soon get updated to [v5](http://unicode.org/emoji/charts-beta/full-emoji-list.html). Also, have a look at [Recommended Emoji ZWJ Sequences](http://unicode.org/emoji/charts-beta/emoji-zwj-sequences.html).

Personally, I’d say anything you do is probably an improvement over the current state, so don’t hesitate to start sending pull requests with your contributions. And a huge **thank you** for doing this!

**Comment by DeeDeeG** [comment]
There are certain glyphs still missing. These are the various family glyphs, and some of the same-sex couple glyphs.

Does anyone know of a free font editor that can work on these files? At the moment, I have tried TruFont, which crashes when I try to edit these glyphs, because the type of curve (quadratic) is not supported properly.

On another note, if anyone knows how to get curves from SVGs, and use them in a glyph, that would help a lot.

I am laying out a strategy for all of the same-sex couple and various family glyphs, but I can't do any of them very easily (or at all) without one of those two things I mentioned above. Regardless, if anyone is able to do these, no need to wait for me to do them. Help is appreciated on this. Here is my plan:

- Family glyphs: Obtain curves from SVGs in this repository. All family combinations are covered in silhouette form, which would carry over very easily to a black/white font.

- Couple with heart glyphs: by deleting and flipping parts of the opposite-sex couple glyph, the same-sex couple glyphs can easily be created. i.e. for the male-male couple: isolate the man in one glyph (he remains offset horizontally by default, which is good), and flip him horizontally. Isolate the man and the heart in a second glyph (delete the woman). Copy the flipped man onto the glyph with the man and the heart. This completes the male couple with heart glyph. Extra credit: flip the second man's hair cowlick, so they are consistent and not obviously mirrored. (mirroring cheapens the glyph IMO). Note: This would probably require a working glyph editor, because the "hair" curve is shared between the man and the woman in the opposite-sex couple with heart glyph (their hair is one contiguous curve).

- Couple kissing glyphs: This would require manually redrawing at least one member of the opposite-sex couple for each same-sex glyph, so this is the most creative-work-intensive out of all of them.

- Couples holding hands: for anyone wondering, these are already there in the b/w font.

**Comment by brawer** [comment]
https://glyphsapp.com/ supports drag-and-drop of SVG files into the glyph editor, but it’s not free (although there’s a free-as-in-beer 30-day trial). I’ve filed a [feature request](https://github.com/trufont/trufont/issues/382) for this in TruFont. Sadly I don’t really have time right now to help with this myself...

**Comment by dougfelt** [comment]
Closing for now due to inactivity.  Please reopen if you need this bug.

**Comment by adrientetar** [comment]
It is now possible to drag and drop SVG files into TruFont.
