### ISSUE TITLE
No color download

### ISSUE THREAD

**Issue by Jogai** [googlei18n/noto-emoji#7]
Only the regular variant is available as ttf

**Comment by brawer** [comment]
At least, we should have a README.md file that explains how to build the font from source, so that downstream distribution maintainers know what to do. For example, it wasn't clear to FreeBSD that this font needs to be built; see [FreeBSD bug 20125](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=201251).

**Comment by s40king** [comment]
👍

**Comment by dougfelt** [comment]
So, we could easily add a built color emoji font, but I'm concerned that we'd need to rebuild it whenever we updated the repo.  So I think it's probably better to update the readme with this information.

**Comment by dougfelt** [comment]
Well, we decided to upload the color font after all.  As the repo updates it may get out of date.  Currently we include the prefix of the repo commit hash from which the font was built into the version string, so it is possible to tell.
