### ISSUE TITLE
Why were all the emoji's changed to be front-facing?

### ISSUE THREAD

**Issue by Jop-V** [googlei18n/noto-emoji#80]
The different poses made them a lot more legible and cute.

**Comment by dougfelt** [comment]
@xiangyexiao, we might want an FAQ about the emoji design...

**Comment by Jop-V** [comment]
Sorry if I annoyed anyone 😉

**Comment by dougfelt** [comment]
No problem.  Some people were fond of the old emoji and sad to see them go.  We don't currently have a good way to generate multiple emoji fonts.

I have not been tagging the emoji before a design change, because the design changes tend to be a bit incremental and I've not thought of it.  You can, if you wish, check out an older version of the repo and build a font with the old emoji in it.  I should make that easier to do.

**Comment by Jop-V** [comment]
Yeah, this is not relevant anymore now, after the complete redesign for Oreo.
